[package]
name = "rust_reporter"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]


[dependencies]
chrono = "0.4.43"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
umya-spreadsheet = "2.3.3"
tera = "1.19"
